#include "nsISupports.idl"

#include "nkICommand.idl"
#include "nkIMenu.idl"
#include "nkIWindow.idl"


// contractid = "@naikai.aegisknight.org/windowing;1"


[scriptable, uuid(be999e44-1dd1-11b2-b1fc-94ad5884f63c)]
interface nkIWindowingService : nsISupports
{
  nkIWindow        createWindow();
  nkIMenu          createMenu();
  nkIMenuItem      createMenuItem(in nkICommand command);

  attribute nkICommand onIdle;

  void run();
  void pumpEvents();
};
