#include "nsISupports.idl"
#include "nkIWindow.idl"


// contractid = "@naikai.aegisknight.org/windowing-system;1"


[scriptable, uuid(be999e44-1dd1-11b2-b1fc-94ad5884f63c)]
interface nkIWindowingSystem : nsISupports
{
  nkIWindow createFrameWindow();

  void processEvents();
};
